server:
  port: ${GATEWAY_PORT:8080}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - JwtAuthFilter
      routes:
        - id: urun-servisi
          uri: http://localhost:8082
          predicates:
            - Path=/urun/**
          filters:
            - name: JwtAuthFilter