server:
  port: ${PORT:8080}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - JwtAuthFilter
      routes:
        - id: urun-servisi
          uri: https://qualitytest-production.up.railway.app
          predicates:
            - Path=/urun/**
          filters:
            - name: JwtAuthFilter